/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';


declare global {

  namespace StencilComponents {
    interface ProjectsList {

    }
  }

  interface HTMLProjectsListElement extends StencilComponents.ProjectsList, HTMLStencilElement {}

  var HTMLProjectsListElement: {
    prototype: HTMLProjectsListElement;
    new (): HTMLProjectsListElement;
  };
  interface HTMLElementTagNameMap {
    'projects-list': HTMLProjectsListElement;
  }
  interface ElementTagNameMap {
    'projects-list': HTMLProjectsListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'projects-list': JSXElements.ProjectsListAttributes;
    }
  }
  namespace JSXElements {
    export interface ProjectsListAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppWelcome {

    }
  }

  interface HTMLAppWelcomeElement extends StencilComponents.AppWelcome, HTMLStencilElement {}

  var HTMLAppWelcomeElement: {
    prototype: HTMLAppWelcomeElement;
    new (): HTMLAppWelcomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  interface ElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-welcome': JSXElements.AppWelcomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppWelcomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface UserDashboard {

    }
  }

  interface HTMLUserDashboardElement extends StencilComponents.UserDashboard, HTMLStencilElement {}

  var HTMLUserDashboardElement: {
    prototype: HTMLUserDashboardElement;
    new (): HTMLUserDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'user-dashboard': HTMLUserDashboardElement;
  }
  interface ElementTagNameMap {
    'user-dashboard': HTMLUserDashboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'user-dashboard': JSXElements.UserDashboardAttributes;
    }
  }
  namespace JSXElements {
    export interface UserDashboardAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
