/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';


declare global {

  namespace StencilComponents {
    interface ProjectCreate {

    }
  }

  interface HTMLProjectCreateElement extends StencilComponents.ProjectCreate, HTMLStencilElement {}

  var HTMLProjectCreateElement: {
    prototype: HTMLProjectCreateElement;
    new (): HTMLProjectCreateElement;
  };
  interface HTMLElementTagNameMap {
    'project-create': HTMLProjectCreateElement;
  }
  interface ElementTagNameMap {
    'project-create': HTMLProjectCreateElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'project-create': JSXElements.ProjectCreateAttributes;
    }
  }
  namespace JSXElements {
    export interface ProjectCreateAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProjectDetail {
      'id': string;
    }
  }

  interface HTMLProjectDetailElement extends StencilComponents.ProjectDetail, HTMLStencilElement {}

  var HTMLProjectDetailElement: {
    prototype: HTMLProjectDetailElement;
    new (): HTMLProjectDetailElement;
  };
  interface HTMLElementTagNameMap {
    'project-detail': HTMLProjectDetailElement;
  }
  interface ElementTagNameMap {
    'project-detail': HTMLProjectDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'project-detail': JSXElements.ProjectDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface ProjectDetailAttributes extends HTMLAttributes {
      'id'?: string;
      'onProjectUpdated'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProjectsListOptionsMenu {

    }
  }

  interface HTMLProjectsListOptionsMenuElement extends StencilComponents.ProjectsListOptionsMenu, HTMLStencilElement {}

  var HTMLProjectsListOptionsMenuElement: {
    prototype: HTMLProjectsListOptionsMenuElement;
    new (): HTMLProjectsListOptionsMenuElement;
  };
  interface HTMLElementTagNameMap {
    'projects-list-options-menu': HTMLProjectsListOptionsMenuElement;
  }
  interface ElementTagNameMap {
    'projects-list-options-menu': HTMLProjectsListOptionsMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'projects-list-options-menu': JSXElements.ProjectsListOptionsMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface ProjectsListOptionsMenuAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProjectsList {

    }
  }

  interface HTMLProjectsListElement extends StencilComponents.ProjectsList, HTMLStencilElement {}

  var HTMLProjectsListElement: {
    prototype: HTMLProjectsListElement;
    new (): HTMLProjectsListElement;
  };
  interface HTMLElementTagNameMap {
    'projects-list': HTMLProjectsListElement;
  }
  interface ElementTagNameMap {
    'projects-list': HTMLProjectsListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'projects-list': JSXElements.ProjectsListAttributes;
    }
  }
  namespace JSXElements {
    export interface ProjectsListAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppWelcome {

    }
  }

  interface HTMLAppWelcomeElement extends StencilComponents.AppWelcome, HTMLStencilElement {}

  var HTMLAppWelcomeElement: {
    prototype: HTMLAppWelcomeElement;
    new (): HTMLAppWelcomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  interface ElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-welcome': JSXElements.AppWelcomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppWelcomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface UserDashboard {

    }
  }

  interface HTMLUserDashboardElement extends StencilComponents.UserDashboard, HTMLStencilElement {}

  var HTMLUserDashboardElement: {
    prototype: HTMLUserDashboardElement;
    new (): HTMLUserDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'user-dashboard': HTMLUserDashboardElement;
  }
  interface ElementTagNameMap {
    'user-dashboard': HTMLUserDashboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'user-dashboard': JSXElements.UserDashboardAttributes;
    }
  }
  namespace JSXElements {
    export interface UserDashboardAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
